name: seni-project
services:
  seni-axon-server:
    image: axoniq/axonserver
    container_name: seni-axon-server
    restart: unless-stopped
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    environment:
      - AXONIQ_AXONSERVER_NAME=Seni Store
      - AXONIQ_AXONSERVER_STANDALONE=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8024/actuator/health" ]
      interval: "50s"
      retries: 3