name: seni-project
services:
  seni-postgres:
    image: postgres:latest
    container_name: seni-postgres
    restart: always
    ports:
      - "5454:5432"
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_BD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      retries: 10