spring:
  application:
    name: type-etablissement-command
  cloud:
    discovery:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_HOST:http://localhost:8761/eureka/}
server:
  port: 6701
axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}