spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: file://${HOME}/Projets/IntelliJ IDEA/config-server/seni-project
          default-label : master
server:
  port: 8888