spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_HOST:http://localhost:8761/eureka/}
server:
  port: 8080